# JVCカメラ パラメータ推定用設定ファイル

# 検証対象のカメラ名
target_camera: camSony2

# 基準点3D座標CSV
points_3d: kijunten_locations.csv

# 基準点2D座標CSV
points_2d: points_2d.csv

# 画像サイズ（4窓の1窓分: 1920/2 x 1080/2）
image_width: 960
image_height: 540
